- name: upgrade
  apt:
    upgrade: dist
    state: present
  become: yes

- name: haproxy is installed
  apt:
    name: haproxy
    state: present
  become: yes

- name: configure haproxy
  template:
    src: "haproxy.cfg.ji2"
    dst: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: restarting and enabling ar
  systemd:
    name: haproxy
    enabled: yes
    state: restarted
  become: yes
