- name: upgrade
  apt:
    upgrade: dist
    state: present
  become: yes


- name: installing jdk
  apt:
    name: "default-jdk"
    state: present
  become: yes

- name: adding repokey for logstash
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  become: yes

- name: adding transport https
  apt:
    name: "apt-transport-https"
    state: present
  become: yes

- name: adding repo for logstash
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    state: present
  become: yes

- name: update and install logstash
  apt:
    name: "elasticsearch"
    update_cache: yes
    state: latest
  become: yes
